# -*- coding: utf-8 -*-
"""Статический анализатор данных.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTU0BFtNwDBKmwbZwrfrNemxcigedznG
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = [43, 49, 25, 22, 28, 36, 36, 28, 45, 21,
        48, 49, 29, 25, 31, 23, 31, 40, 35, 32,
        18, 26, 43, 33, 36, 25, 38, 27, 39, 33, 26,
        43, 32, 34, 35, 35, 44, 21, 31, 37]
print("1 пункт")
n=len(data)
k=int(np.ceil(1*3.322*np.log10(n)))
print("Количество интевалов k =",k)
x_min=min(data)
x_max=max(data)
r=x_max-x_min
h=np.ceil(r/k)
print("Ширина интервала h =",h)

intervals=[]
x_min=x_min-2
for i in range (k+1):
  a_i = x_min + i * h
  intervals.append(a_i)
print("Границы интервалов:")
for i in range(len(intervals) - 1):
    print(f"[{intervals[i]:.2f}, {intervals[i+1]:.2f})")

frequencies = [0] * k
for value in data:
    for i in range(k):
        if intervals[i] <= value < intervals[i + 1]:
            frequencies[i] += 1
            break
    else:
        if value == intervals[-1]:
            frequencies[-1] += 1

print("Интервалы и частоты:")
for i in range(k):
    print(f"[{intervals[i]}, {intervals[i+1]}): {frequencies[i]}")
print("Объем выборки n =", sum(frequencies))

relative_frequency=[0]*k
for i in range(k):
  relative_frequency[i]=frequencies[i]/n

print("Интервальный ряд относительных частот:")
for i in range(k):
    print(f"[{intervals[i]}, {intervals[i+1]}): {relative_frequency[i]:.3f}")

print("2 пункт")
print("Размах вариации r = ", r)
print("Количество интервалов k = ",9)
print("Ширина интервала h =",h)

print("Дискретный ряд распределения")
midpoints = []

for i in range(len(intervals) - 1):
    a_i = intervals[i]
    a_i_plus_1 = intervals[i + 1]
    midpoint = (a_i + a_i_plus_1) / 2
    midpoints.append(midpoint)
print("x_i, n_i/n")
for i in range(len(midpoints)):
    print(f"{midpoints[i]}: {relative_frequency[i]:.3f}")

print("Накопленные частоты")
cumulative_frequencies = []
cumulative_sum = 0
for freq in frequencies:
    cumulative_sum += freq
    cumulative_frequencies.append(cumulative_sum)

cumulative_relative_frequencies = []
for cf in cumulative_frequencies:
  cumulative_relative_frequency = cf / n
  cumulative_relative_frequencies.append(cumulative_relative_frequency)
print(f"{'x_i':<10} {'n_i':<15} {'n_i/n':<30}")
for i in range(len(intervals) - 1):
    x_i = f"{midpoints[i]}"
    n_i = cumulative_frequencies[i]
    n_i_n = cumulative_relative_frequencies[i]
    print(f"{x_i:<10} {n_i:<15} {n_i_n:.3f}")

print("3 пункт")
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.bar(intervals[:-1], relative_frequency, width=h, edgecolor='black')
plt.title('Гистограмма относительных частот')
plt.xticks(intervals[:-1], rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(midpoints, relative_frequency, marker='o', linestyle='-', color='b')
plt.title('Полигон относительных частот')
plt.grid(True)
plt.show()

left_bounds = intervals[:-1]
plt.figure(figsize=(10, 6))
plt.plot(left_bounds, cumulative_relative_frequencies, marker='o', linestyle='-',color='b')
plt.title('Кумулята')
plt.xticks(left_bounds, rotation=45)
plt.grid(True)
plt.show()

print("4 пункт")

print("Эмпирическая функция распределения")
print("F(x) = {")
for i in range(len(intervals) - 1):
    if i == 0:
        print(f"Если x <= {intervals[i]}, то F(x)=0")
    print(f"Если {intervals[i]} < x <= {intervals[i+1]},то F(x) = {cumulative_relative_frequencies[i]}")
print(f"    1, если x > {intervals[-1]},")
print("}")


plt.figure(figsize=(10, 6))
plt.step(midpoints, cumulative_relative_frequencies, where='post')
plt.yticks(np.arange(0, 1.1, 0.2))
plt.xticks(np.arange(18, 51, h))
plt.title('Эмпирическая функция распределения')
plt.xlabel('Значения данных (x)')
plt.ylabel('F(x)')
plt.grid(True, linestyle='--')
plt.show()

from collections import Counter
from math import sqrt
from tabulate import tabulate

print("5 пункт")
print("1) Мода")
n_MO=max(frequencies)
index_MO = frequencies.index(n_MO)
x_O = intervals[index_MO]
n_MO1=frequencies[index_MO-1]
n_MO2=frequencies[index_MO+1]
x_MO=round(x_O+h*((n_MO-n_MO1)/(2*n_MO-n_MO1-n_MO2)),3)
print("Мода x_MO =",x_MO)
print()
print("2) Медиана")
n_2=int(n/2)
n_ME=data[20]
cumulative_at_modal = frequencies[index_MO]
S_ME1=cumulative_frequencies[index_MO-1]
x_ME=round(x_O+h*((n_2-S_ME1)/(cumulative_at_modal)),3)
print("Медиана x_ME =",x_ME)
print()

print("3) Метод произведений для вычисления выборочных среденей, дисперсии, средне квадратичного отклонения, начальных и центральных моментов")
midpoints = [(intervals[i] + intervals[i+1]) / 2 for i in range(k)]

relative_frequency=[0]*k
for i in range(k):
  relative_frequency[i]=frequencies[i]
relative_freq_MO = relative_frequency[index_MO]

index = relative_frequency.index(relative_freq_MO)
ui = [i - index for i in range(k)]
niui=[int(relative_frequency[i]*ui[i]) for i in range(k)]
sniui=sum(niui)
niui2=[int(relative_frequency[i]*ui[i]*ui[i]) for i in range(k)]
sniui2=sum(niui2)
niui3=[int(relative_frequency[i]*ui[i]*ui[i]*ui[i]) for i in range(k)]
sniui3=sum(niui3)
niui4=[int(relative_frequency[i]*ui[i]*ui[i]*ui[i]*ui[i]) for i in range(k)]
sniui4=sum(niui4)
niui4_1=[int(relative_frequency[i]*((ui[i]+1)**4)) for i in range(k)]
sniui4_1=sum(niui4_1)

table_data = list(zip(midpoints, frequencies,ui, niui, niui2, niui3, niui4, niui4_1))
headers = ["x_i", "n_i","u_i" "n_i*u_i", "n_i*u_i^2", "n_i*u_i^3", "n_i*u_i^4", "n_i*(u_i+1)^4"]
print(tabulate(table_data, headers=headers, tablefmt="github"))

print("Начальные моменты")
M_1=round(sniui/n,3)
print("M_1 =",M_1)

M_2=round(sniui2/n,2)
print("M_2 =",M_2)

M_3=round(sniui3/n,2)
print("M_3 =",M_3)

M_4=round(sniui4/n,2)
print("M_4 =",M_4)

print("Выборочная средняя")
x_v=round(M_1*h+midpoints[index],3)
print("x_v =",x_v)

print("Выборочная дисперсия")
D_v=round((M_2-M_1**2)*h*h,4)
print("D_v =",D_v)

print("Выборочное средене квадратическое отклонение")
sigma=round(sqrt(D_v),3)
print("sigma =","{:.4f}".format(sigma))

m_3=round((M_3-3*M_1*M_2+2*M_1**3)*h**3,4)
print("m_3 =",m_3)

m_4=round((M_4-4*M_1*M_3+6*M_1*M_1*M_2-3*M_1**4)*h**4,4)
print("m_4 =","{:.4f}".format(m_4))

print("Коэффициенты")
v_s=round((sigma/x_v)*100,2)
print("v_s =","{:.2f}".format(v_s),"%")

a_s=round(m_3/(sigma**3),3)
print("a_s =","{:.4f}".format(a_s))

e_k=round(m_4/(sigma**4)-3,3)
print("e_k =","{:.2f}".format(e_k))

from math import pi
import matplotlib.pyplot as plt
from tabulate import tabulate

print("6 пункт")
st1=[round(midpoints[i] - x_v, 1) for i in range(k)]
st2=[round((midpoints[i] - x_v)/sigma, 5) for i in range(k)]
st3=[round((1/(sqrt(2*pi)))*2.71**((-1)*((st2[i]**2)/(2))),4) for i in range(k)]
st4=[round(19.4*st3[i]) for i in range(k)]
table_data = list(zip(st1, st2, st3, st4))
headers = ["st1", "st2", "st3", "st4"]
print(tabulate(table_data, headers=headers, tablefmt="github"))

plt.figure(figsize=(8, 5))
plt.plot(midpoints, st4, marker='o', linestyle='-', color='blue', label='теоретическая нормальная кривая')
plt.plot(midpoints, frequencies, marker='s', linestyle='--', color='green', label='эмпирическая кривая')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

from tabulate import tabulate
from scipy.stats import chi2

print("7 пункт")
alfa=0.05

st_1=frequencies
st_2=st4
st_3=[st_1[i]-st_2[i] for i in range(k)]
st_4=[st_3[i]**2 for i in range(k)]
st_5=[round(st_4[i]/st_2[i],3) for i in range(k)]
st_6=[st_1[i]**2 for i in range(k)]
st_7=[round(st_6[i]/st_2[i],3) for i in range(k)]
table_data = list(zip(st_1, st_2, st_3, st_4, st_5, st_6, st_7))
headers = ["st_1", "st_2", "st_3", "st_4", "st_5", "st_6", "st_7"]
print(tabulate(table_data, headers=headers, tablefmt="github"))

kci_max=sum(st_5)
contr=sum(st_7)-sum(st_2)
print(k)
vi=k-3
print("vi =",vi)
ksi_crit=chi2.ppf(1 - alfa, vi)
if (kci_max<ksi_crit):
  print(kci_max,"<",ksi_crit)
  print("Гипотеза не отвергается")
else:
  print(kci_max,">",ksi_crit)
  print("Гипотеза отвергается")

print("8 пункт")
gama=0.95
f_t=gama/2
t=1.96
delta=round((t*sigma)/(sqrt(n)),2)
left=round(x_v-delta,2)
right=round(x_v+delta,2)
print(left,"<","MX","<",right)
q=0.24
left2=round(sigma*(1-q),2)
right2=round(sigma*(1+q),2)
print(left2,"<","sigma","<",right2)